In [1]:
import numpy as np

def sigmoid(x,deriv=False): # derivative = True, compute the derivative of the point
    if deriv:
        return x*(1-x) # assumes x is sigmoid(x), sigmoid(sigmoid(z),deriv=True)
    return 1/(1+np.exp(-x)) # sigmoid(z,deriv=False)

# function return the weight of the first layer
def run_net(X,y,activation_function=sigmoid,passes=10): 
    #passes: how many times you want to do feed forward
    np.random.seed(1)
    syn0 = 2*np.random.random((3,1)) - 1  # generate a (3,1) random matrix as the weight
    for i in range(0,passes):
        level_0 = X #input layer has no function application
        level_1 = activation_function(np.dot(level_0,syn0)) # we take all rows/examples into the network, parallel processing
                                    # (4,1) level 1 shape
        level_1_error = y - level_1 #error
        level_1_delta = level_1_error * activation_function(level_1,True) # make incremental changes each loop, to find all weights optimal
                                                                            # multiple the error by the slope of the point
        syn0 += np.dot(level_0.T,level_1_delta)                             # why? beyound the scope, mathmatics
    return syn0

In [2]:
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  # X shape: (4,3)
y = np.array([[0,0,1,1]]).T # y shape: (4,)

final_weights = run_net(X,y,sigmoid,10)
final_weights

array([[ 1.72057624],
       [ 0.23669265],
       [-0.84074522]])

In [3]:
test_X = np.array([[1,1,1],[0,1,1],[1,0,0],[0,0,1]])
sigmoid(np.dot(test_X,final_weights))

array([[0.75334332],
       [0.35341708],
       [0.84820304],
       [0.30137786]])

In [4]:
def sigmoid(x,deriv=False):
    if deriv:
        return x*(1-x)
    return 1/(1+np.exp(-x))

def run_net(X,y,activation_function=sigmoid,passes=10):
    import time
    np.random.seed(1)
    syn0 = 2*np.random.random((3,4)) - 1
    syn1 = 2*np.random.random((4,1)) - 1

    for i in range(passes):
        level_0 = X
        level_1 = activation_function(np.dot(level_0,syn0))
        level_2 = activation_function(np.dot(level_1,syn1))

        #Backpropagate
        level_2_error = y - level_2

        level_2_delta = level_2_error*activation_function(level_2,deriv=True)

        level_1_error = level_2_delta.dot(syn1.T)

        level_1_delta = level_1_error * activation_function(level_1,deriv=True)

        syn1 += level_1.T.dot(level_2_delta)
        syn0 += level_0.T.dot(level_1_delta)
    
    return syn0,syn1

In [5]:
level_0 = test_X
syn0,syn1 = run_net(X,y,activation_function=sigmoid,passes=100)
level_1 = sigmoid(np.dot(level_0,syn0))
level_2 = sigmoid(np.dot(level_1,syn1))
level_2

array([[0.90612169],
       [0.07247266],
       [0.94324574],
       [0.08962597]])