***I affirm that I will not plagiarize, use unauthorized materials, or give or receive illegitimate help on assignments, papers, or examinations. I will also uphold equity and honesty in the evaluation of my work and the work of others. I do so to sustain a community built around this Code of Honor.***

If you agree to abide by this honor code please enter your name in the box below

In [ ]:
Weiqi Yu

**Q1)** The  webpage "https://www.atptour.com/en/news/story-of-the-season" lists the tournaments of the ATP tennis season this year. 
Write a program that uses BeautifulSoup and webscraping to populate a dataframe **ATP_Stories_2022** with columns *Month,Story_Title,Story_Link,Score* that parses this webpage as follows: <tab><tab>**[40 Points Total]**
 
- Find the month, story_titles within each month and their corresponding story_links in the landing page **[20 Points}**<br>
- For each story_link visit the corresponding page and grab the final score by looking in the first two paragraphs. If not found, insert N/A for score column (*Hint: re.findall('\d\-\d','He won 6-4,7-6') will return [6-4,7-6]*) **[15 Points]**<br>
- return a dataframe containing the above columns **[5 POINTS]**

***Notes***

*Use the cloudscraper library to get around captcha issues that may otherwise prevent you from programmatically accessing the data on the page.* <br>
*Use pd.concat() and not df.append() when creating your dataframe as the latter is deprecated* <br>
*Only fetch what is available on the landing page (no need to hit **LOAD MORE** button at the bottom of the page)*


In [87]:
# Here's some code to get you started:
!pip install cloudscraper
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup
import cloudscraper

scraper = cloudscraper.create_scraper()
url = "https://www.atptour.com/en/news/story-of-the-season" 
scraper = cloudscraper.create_scraper() 
response = scraper.get(url)
if not response.status_code == 200: 
    None 
try: 
    results_page = BeautifulSoup(response.content,'lxml') 
except: 
    None 

In [ ]:
ATP_Stories_2022 = pd.DataFrame()

In [172]:
url = 'https://www.atptour.com/en/news/story-of-the-season'
response = requests.get(url) 
if response.status_code == 200:
    print("Success")
else:
    print("Failure")

Success


In [173]:
import re
results_page = BeautifulSoup(response.content,'lxml')
results = results_page.find_all('div', {"class": "timeline-item-inner"})
type(results)

bs4.element.ResultSet

In [174]:
results

[<div class="timeline-item-inner">
 <a class="timeline-thumbnail" href="/en/news/auger-aliassime-wolf-florence-2022-final">
 <div class="lazy-loader" data-src="/-/media/images/news/2022/10/16/19/26/felix-florence-2022-final-celebration.jpg?h=238&amp;sc=0&amp;w=420&amp;hash=503FF83702687EDFE77D6397F6262EFF" data-type="background" style="-webkit-transform: translateZ(0)">
 </div>
 </a>
 <div class="timeline-item-info">
 <h3 class="listing-title">
 <a href="/en/news/auger-aliassime-wolf-florence-2022-final">
 							Felix Wins Florence Title, Improves Turin Qualification Hopes
 						</a>
 </h3>
 <div class="listing-category">
 <span class="listing-category-title">
 									Florence
 								</span>
 </div>
 </div>
 </div>,
 <div class="timeline-item-inner">
 <a class="timeline-thumbnail" href="/en/news/florence-2022-doubles-final">
 <div class="lazy-loader" data-src="/-/media/images/news/2022/10/16/15/25/florence-doubles-2022-final-sunday-1.jpg?h=238&amp;sc=0&amp;w=420&amp;hash=37BA5E1D

In [161]:
time = []

In [175]:
for item in timeline:
    pattern = r'[A-Z][a-z]*'
    # print(item.get_text())
    month = re.search(pattern,item.get_text())
    time.append(month.group(0).strip())
time

['October', 'September', 'August', 'July', 'June', 'May', 'April', 'March']

In [176]:
titles = results_page.find_all('h3', {"class": "listing-title"})
story_title = []
for item in titles:
    item.find('a').get_text().strip()
    # pattern = r'[A-Z][a-z]*'
    # print(item.get_text())
    # month = re.search(pattern,item.get_text())
    story_title.append(item.find('a').get_text().strip())
story_title

['Felix Wins Florence Title, Improves Turin Qualification Hopes',
 'Mahut/Roger-Vasselin Triumph In Florence',
 'Rublev Reigns In Gijon',
 'Gonzalez/Molteni Lift Gijon Trophy',
 'Djokovic Triumphs In Astana',
 'Fritz Fires Past Tiafoe To Tokyo Title',
 'Mektic/Pavic Clinch Astana Crown',
 'McDonald/Melo Win Tokyo Title in Team Debut',
 'Djokovic Completes Dominant Week, Beats Cilic For Tel Aviv Title',
 'Bopanna/Middelkoop Earn 1st Team Title In Tel Aviv',
 'Huesler Clinches First Title In Sofia',
 'Klaasen/Lammons Cruise To Seoul Title',
 'Matos/Vega Hernandez Triumph In Sofia',
 'Nishioka Sinks Shapo For Seoul Crown',
 'Hometown Hero: Nakashima Wins First ATP Title In Native San Diego',
 'Lammons/Withrow Claim First ATP Tour Title In San Diego',
 'Tiafoe Captures Laver Cup For Team World',
 'Silky Sonego Charges To Metz Title',
 'From Foe To Friend: Nys/Zielinski Take Maiden Title In Metz',
 'The Grit & Grace Of Roger Federer',
 'Living The Dream: How Carlos Alcaraz Hit No. 1 At 19',

In [177]:
ATP_Stories_2022['title'] = story_title
ATP_Stories_2022 = ATP_Stories_2022[:-1]

In [178]:
links = results_page.find_all('div', {"class": "timeline-item-inner"})
story_link = []
for item in links:
    # item.find('a').get_text().strip()
    # pattern = r'[A-Z][a-z]*'
    # print(item.get_text())
    # month = re.search(pattern,item.get_text())
    story_link.append(item.find('a').get('href'))
story_link

['/en/news/auger-aliassime-wolf-florence-2022-final',
 '/en/news/florence-2022-doubles-final',
 '/en/news/korda-rublev-gijon-2022-final-sunday',
 '/en/news/gijon-2022-doubles-final',
 '/en/news/djokovic-tsitsipas-astana-2022-final',
 '/en/news/fritz-tiafoe-tokyo-2022-sunday-final',
 '/en/news/astana-2022-doubles-final-sunday',
 '/en/news/mcdonald-melo-tokyo-2022-sunday-doubles-final',
 '/en/news/djokovic-cilic-tel-aviv-2022-final',
 '/en/news/tel-aviv-2022-doubles-final',
 '/en/news/huesler-rune-sofia-2022-sunday',
 '/en/news/klaasen-lammons-seoul-2022-sunday-doubles-final',
 '/en/news/sofia-2022-doubles-final',
 '/en/news/shapovalov-nishioka-seoul-2022-sunday-final',
 '/en/news/nakashima-giron-san-diego-2022-final',
 '/en/news/lammons-withrow-san-diego-2022-doubles-final',
 '/en/news/laver-cup-2022-sunday',
 '/en/news/bublik-sonego-metz-2022-sunday-final',
 '/en/news/nys-zielinski-metz-2022-sunday-doubles-final',
 '/en/news/roger-federer-retirement-longform-essay',
 '/en/news/carlos-a

In [179]:
ATP_Stories_2022['links'] = story_link
ATP_Stories_2022

title  \
0   Felix Wins Florence Title, Improves Turin Qual...   
1            Mahut/Roger-Vasselin Triumph In Florence   
2                              Rublev Reigns In Gijon   
3                  Gonzalez/Molteni Lift Gijon Trophy   
4                         Djokovic Triumphs In Astana   
..                                                ...   
95  Q1 Review: Canada's Cup, Nadal's Perfect Start...   
96  Wild Cards Hurkacz/Isner Cool Koolhof/Skupski ...   
97  Fritz Ends Nadal's Perfect Season To Win India...   
98  Isner/Sock Claim Second Indian Wells Title Tog...   
99   Murray Milestone: Briton Reaches 700 Career Wins   

                                                links  
0   /en/news/auger-aliassime-wolf-florence-2022-final  
1                /en/news/florence-2022-doubles-final  
2       /en/news/korda-rublev-gijon-2022-final-sunday  
3                   /en/news/gijon-2022-doubles-final  
4       /en/news/djokovic-tsitsipas-astana-2022-final  
..                                                ...  
95  /en/news/nadal-medvedev-felix-shapovalov-first...  
96  /en/news/hurkacz-isner-koolhof-skupski-miami-2...  
97       /en/news/nadal-fritz-indian-wells-2022-final  
98           /en/news/indian-wells-2022-doubles-final  
99              /en/news/murray-2022-700-wins-tribute  

[100 rows x 2 columns]

**Q2)** As the Chief Data Officer of Widgets Inc., you are tasked with  running some analytics on the company's customers. You ask your assistant to send you two data files: **[20 Points]**<br>

*Customers.csv* which lists all customers of Widgets Inc.<br>
*Orders.csv* which lists all orders placed in 2019 & 2020. <br>

**Company_ID** in  *Customers.csv*  is the same attribute as **Customer_ID** in  *Orders.csv*

- Compile a list of customers who have placed multiple orders over the course of 2019-2020 **[10 Points]**
- Identify customers who placed multiple orders in a single month **[10 Points]**

***Note: Your list should only contain the names of customers in alphabetical order***

 ***You MUST use Dataframe and Series object operations such as apply, groupby, merge, concat and masking to obtain the above lists. Anything else will receive 0 credit even if you somehow managed to get the right answer!***



In [57]:
customer = pd.read_csv('Customers.csv')
customer.head()

Company_ID         Company_Name
0           1  Abbott Laboratories
1           2          AbbVie Inc.
2           3          ABIOMED Inc
3           4        Accenture plc
4           5  Activision Blizzard

In [44]:
order = pd.read_csv('Orders.csv')
order

Date  Customer_ID  Amount
0    2019-07-12            2    $114
1    2019-11-19          235  $13395
2    2020-06-17           69   $3933
3    2020-01-20          337  $19209
4    2019-12-01          146   $8322
..          ...          ...     ...
160  2020-03-28          486  $27702
161  2019-12-08            9    $513
162  2020-10-27          429  $24453
163  2019-10-11          403  $22971
164  2019-12-30          267  $15219

[165 rows x 3 columns]

In [45]:
type(order['Date'].iloc[0])

str

In [46]:
order['Date'] = pd.to_datetime(order['Date'])

In [56]:
grouped = order.groupby('Customer_ID').count()
multi_purchase = grouped[grouped['Date']>1]
multi_purchase

Date  Amount
Customer_ID              
44              3       3
116             3       3
139             2       2
146             2       2
170             2       2
194             2       2
210             2       2
249             2       2
253             2       2
269             2       2
277             2       2
279             2       2
280             2       2
291             3       3
296             2       2
301             2       2
335             2       2
347             2       2
349             2       2
357             2       2
366             2       2
378             2       2
421             3       3
426             2       2
451             2       2

In [60]:
final = pd.merge(multi_purchase,customer,left_index=True, right_on='Company_ID')
final

Date  Amount  Company_ID               Company_Name
43      3       3          44         Apache Corporation
115     3       3         116          Colgate-Palmolive
138     2       2         139       Delta Air Lines Inc.
145     2       2         146  Discovery, Inc. (Class A)
169     2       2         170              EOG Resources
193     2       2         194  FleetCor Technologies Inc
209     2       2         210           General Electric
248     2       2         249                Intel Corp.
252     2       2         253          Interpublic Group
268     2       2         269       Kansas City Southern
276     2       2         277               Kohl's Corp.
278     2       2         279                 Kroger Co.
279     2       2         280              L Brands Inc.
290     3       3         291                  Linde plc
295     2       2         296                Lowe's Cos.
300     2       2         301         Marathon Petroleum
334     2       2         335              Newell Brands
346     2       2         347             NortonLifeLock
348     2       2         349                 NRG Energy
356     2       2         357                      ONEOK
365     2       2         366                Pentair plc
377     2       2         378                  PPL Corp.
420     3       3         421         Southwest Airlines
425     2       2         426              Stryker Corp.
450     2       2         451         Tyler Technologies

In [71]:
answer_1 = final['Company_Name'].to_list()
sorted(answer_1)

['Apache Corporation',
 'Colgate-Palmolive',
 'Delta Air Lines Inc.',
 'Discovery, Inc.\xa0(Class A)',
 'EOG Resources',
 'FleetCor Technologies Inc',
 'General Electric',
 'Intel Corp.',
 'Interpublic Group',
 'Kansas City Southern',
 "Kohl's Corp.",
 'Kroger Co.',
 'L Brands Inc.',
 'Linde plc',
 "Lowe's Cos.",
 'Marathon Petroleum',
 'NRG Energy',
 'Newell Brands',
 'NortonLifeLock',
 'ONEOK',
 'PPL Corp.',
 'Pentair plc',
 'Southwest Airlines',
 'Stryker Corp.',
 'Tyler Technologies']

In [47]:
type(order['Date'].iloc[0])

pandas._libs.tslibs.timestamps.Timestamp

In [63]:
order['month'] = order['Date'].apply(lambda x: x.month)
order

Date  Customer_ID  Amount  month
0   2019-07-12            2    $114      7
1   2019-11-19          235  $13395     11
2   2020-06-17           69   $3933      6
3   2020-01-20          337  $19209      1
4   2019-12-01          146   $8322     12
..         ...          ...     ...    ...
160 2020-03-28          486  $27702      3
161 2019-12-08            9    $513     12
162 2020-10-27          429  $24453     10
163 2019-10-11          403  $22971     10
164 2019-12-30          267  $15219     12

[165 rows x 4 columns]

In [68]:
grouped_1 = order.groupby(['Customer_ID','month']).count()
grouped_1

Date  Amount
Customer_ID month              
1           9         1       1
2           7         1       1
6           3         1       1
9           12        1       1
15          4         1       1
...                 ...     ...
477         9         1       1
482         11        1       1
486         3         1       1
492         12        1       1
500         12        1       1

[163 rows x 2 columns]

In [69]:
multi_month_purchase = grouped_1[grouped_1['Amount']>1]
multi_month_purchase

Date  Amount
Customer_ID month              
269         9         2       2
451         9         2       2

In [73]:
final_2 = pd.merge(multi_month_purchase,customer,left_on='Customer_ID', right_on='Company_ID')
final_2

Date  Amount  Company_ID          Company_Name
0     2       2         269  Kansas City Southern
1     2       2         451    Tyler Technologies

In [74]:
answer_2 = final_2['Company_Name'].to_list()
sorted(answer_2)

['Kansas City Southern', 'Tyler Technologies']

**Q3. [10 Points]**

Given an array **ax**:<br>
[[ 0  2  4]<br>
 [ 6  8 10]<br>
 [12 14 16]<br>
 [18 20 22]]<br>
 
and an array **ay**:

[0 1 2 3 4]

How would you use array reshaping and broadcasting to combine **ax** and **ay** to produce the array **az** below?  

        [[[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8],
        [ 0,  4,  8, 12, 16]],

       [[ 0,  6, 12, 18, 24],
        [ 0,  8, 16, 24, 32],
        [ 0, 10, 20, 30, 40]],

       [[ 0, 12, 24, 36, 48],
        [ 0, 14, 28, 42, 56],
        [ 0, 16, 32, 48, 64]],

       [[ 0, 18, 36, 54, 72],
        [ 0, 20, 40, 60, 80],
        [ 0, 22, 44, 66, 88]]]
       
       

In [26]:
import numpy as np
import pandas as pd
ax = [[ 0,2,4],
 [6,8,10],
 [12,14,16],
 [18,20,22]]
ay = [0,1,2,3,4]

In [27]:
ax = np.array(ax)
ay = np.array(ay)

In [28]:
az = ax[:,:,np.newaxis]*ay
az

array([[[ 0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8],
        [ 0,  4,  8, 12, 16]],

       [[ 0,  6, 12, 18, 24],
        [ 0,  8, 16, 24, 32],
        [ 0, 10, 20, 30, 40]],

       [[ 0, 12, 24, 36, 48],
        [ 0, 14, 28, 42, 56],
        [ 0, 16, 32, 48, 64]],

       [[ 0, 18, 36, 54, 72],
        [ 0, 20, 40, 60, 80],
        [ 0, 22, 44, 66, 88]]])